service: serverless-express

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: edu

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamoDb:*"
      Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1


functions:
  lambda-api:
    handler: src/launch/lambda.api
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
resources:
  Resources:
    logsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: logs
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1